### ISSUE TITLE
won't build on linux

### ISSUE THREAD

**Issue by typorian** [fredizzimo/infinity_ergodox#10]
Here is ther error message:

[...]
Compiling keymap_plain.c
Compiling matrix.c
Compiling keymap_common.c
Compiling led.c
Compiling user_hooks.c
Compiling gdisp_lld_ST7565.c
./drivers/gdisp/st7565ergodox/gdisp_lld_ST7565.c:37:48: fatal error: drivers/gdisp/ST7565ergodox/st7565.h: No such file or directory
 #include "drivers/gdisp/ST7565ergodox/st7565.h"
                                                ^
compilation terminated.
make: **\* [build/obj/gdisp_lld_ST7565.o] Error 1

**Comment by fredizzimo** [comment]
Hi,

I don't have access to my computer right now. But the fix should be to change the include in gdisp_lld_ST7565.c from  #include "drivers/gdisp/ST7565ergodox/st7565.h" to #include "drivers/gdisp/st7565ergodox/st7565.h". Notice the lowercase st.

**Comment by typorian** [comment]
This works, thank you.

**Comment by fredizzimo** [comment]
Fixed by commit 10f3353e5e92d74ec7b704460ce6ffd6731fe1e0
